Feature/#2/make pipeline
trash-dev-camp/lgbot-twitterbot pull request #7
Opened 2018-02-21 18:52 UTC by kazuki-m

特にTwitter投稿クラス見て欲しいです。
複数回動かすと、二重に認証情報を得るため、初期化していますが、
無駄な処理になっていないか見て欲しいです。
また、Merge後ですが、"lgbot-twitterbot/src/main/java/Main.java"も合わせてお願いします。

※山程issue立てましたが、
issue3をマージしなければ、issue4の差分が上手く表示されない、issue4をマージしなければ(略)
の状態になっていると思いましたので、一旦リモートブランチを削除し、当ブランチに最新版を全て投げました。（折角運用細かく決めてくださったのにすみません）

2018-02-22 02:11 UTC, yoshioH reviewed
Twitterに投稿する部分といっても基本的にAPIを呼び出しているだけなので、特に問題ないと思います。

2018-02-22 02:11 UTC, yoshioH commented on build.gradle
> +   	compile group: 'com.google.cloud.dataflow', name: 'google-cloud-dataflow-java-sdk-all', version: '2.2.0'
凄い細かいけど、タブインデントかスペースインデントかは統一するクセをつけるといいよ。

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/constants/Attribute.java
> +public enum Attribute{
何の属性を示すのかパッケージ＋名前（完全修飾名）で分かるようにしてくださいな。
ただ、一通りできた今現在、パッケージを再構築すると大変なことになりそうだから、修正はクラス名だけでいいよ。

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/constants/Attribute.java
> +	public String getString() {
toStringをOverrideしない理由は？

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/doFn/ConvertDoFn.java
> + * PubSubメッセージのURLを取得する。
名前はConvertなのにJavadocはURL取得、でも実際の処理はPubsubMessageを右から左に素通りさせているだけ。
なんだこれ♪L( ＾ω＾ )┘
別の何かをしたかった名残かな？今現在、処理はないけど、クラスとして残すべという判断なら残しておいていいよ。

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/doFn/FilterDoFn.java
> +		if (c.element().getAttribute("siteType").equals(old.getString())) {
この判定メソッドはAttributeクラスに持っていこう。

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/doFn/FilterDoFn.java
> + * サイトのタイプを取得する。oldの場合、Pcollectionを出力する。
取得じゃなくてフィルタリングだよね？
それと、Pcollectionを出力するって説明は混乱するから要らないよー。

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> + * サイトタイプがoldであるサイトのURLをTwitterに投稿する。
oldであるサイトのURLをTwitterに投稿するのではなく、連携されたURLをTwitterに投稿するクラス/機能だよね？
なら、そう書いた方がいいよ。oldかどうかも判定しているように読める。

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> +		// Twitter認証情報を初期化する。
認証情報の初期化と設定は別メソッドに切り出して。このメソッドの主な目的はpostだから、それ以外のことをなるべく意識したくない。

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> +			lgbot.updateStatus(new String(c.element().getPayload()));
URLだけぶん投げるのも芸がないし、煽り文句とか入れちゃう？
（やらなくていいｗ）

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> +			e.printStackTrace();
LOGGER.errorで出力してあげませふ。

2018-02-22 02:11 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> +			e.printStackTrace();
warnでもいいかも。

2018-02-22 02:26 UTC, yoshioH reviewed
Main.java読むの忘れてたので、読んだ分を追記。

2018-02-22 02:26 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> +	public TwitterPostDoFn(String[] oauth) {
Main.javaを読んで思ったけど、oauthってなんで配列なの？そのままMyOption使ってもいいんじゃね？
今更な話だし配列で押し切ってもいいけど、配列を使うならば添え字のどこに何が入っているかを定数定義してあげましょう。ただ、もし、この手の定義をプログラム内に数値リテラル書きするのは良くないって知っててやっているのであれば修正しなくてもOK。

2018-02-22 02:30 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> +	public TwitterPostDoFn(String[] oauth) {
この前、MyOptionを使わない理由を聞いた気がするけど、いまいち理解できてないのでもう一度教えてー。

2018-02-22 08:22 UTC, ryutah commented
対応大変だろうし、平山さんの指摘の返答とか終わったら改めて確認しますね。

2018-02-22 14:11 UTC, kazuki-m commented on src/main/java/doFn/TwitterPostDoFn.java
> +	public TwitterPostDoFn(String[] oauth) {
>今更な話だし配列で押し切ってもいいけど、配列を使うならばどこ(添え字)に何が入っているかを定数定義してあげましょう。ただ、もし、この手の定義をプログラム内に数値リテラル書きするのは良くないって知っててやっているのであれば修正しなくてもOK。

知りませんでした。

前回は、手続き型のメンバ変数を使わないプログラムしか読んでいなかったため、メンバ変数を使うという発想が欠けていました。

今回はインスタンス化の際にoption.get~で書こうと思いましたが、
引数を４つ渡すのは大きくなりすぎると思ったため、配列に詰めて渡しました。
たしかに自分でも違和感はありましたが、実引数を４つ記載するよりは読みやすいかと思いました。

2018-02-22 14:20 UTC, kazuki-m commented on src/main/java/constants/Attribute.java
> +	public String getString() {
無いです。
新たなクラス作成したらtoStringオーバーライドするという認識が欠けてました。

2018-02-23 02:06 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> +	public TwitterPostDoFn(String[] oauth) {
ごめん、僕の伝え方が悪かったね。
配列にするメリットもあまり感じないし、getOauthメソッド経由せずに"MyOption option"そのまま渡せば？って意味だよ。

new TwitterPostDoFn(getOauth(option))
ではなく
new TwitterPostDoFn(option)
で渡せるようにした方がいいんじゃね？って意味です。

ただ、以前の打ち合わせの時になんかよくわからないけどうまくいかないって話もあったから、もしかしたらそれかなぁって思って、MyOptionを使わない理由を改めて聞いた次第。

2018-02-23 02:25 UTC, yoshioH commented on src/main/java/constants/Attribute.java
> +	public String getString() {
ごめん、言葉足らずだったね。
toStringは必要に応じてOverrideすればいいよ。toStringとgetStringを別の用途で使っているのであればいいんだけど、toStringとして使っているのであれば、そのままtoStringを使うべきだというだけです。
getStringだとStringという名前のプロパティを取得するという意味になります。
でも実際は、宣言名と一致させた文字列定義を取得しているだけなので、toStringと言った方が適切だと僕は思います。
もし、@kazuki-mが宣言名と文字列定義は必ずしも一致するものではないというスタンスに立つのであれば、getTextDefineのようにプロパティと一致させながらメソッドを切ってあげた方が良いと思います。（textというメンバ変数名もちょっと雑なネーミング）

もう少し深いことを言うと、EnumのtoStringはname()を呼び出してenumの宣言名を取得する実装になっているからOverrideせずにtoStringしたり、nameメソッド使うのもOK。

2018-02-23 02:30 UTC, yoshioH commented on src/main/java/constants/Attribute.java
> +	public String getString() {
ネーミングについては、まだプログラミング初めてまだ半年ということでかなり厳しめに指摘しています。（逆に言うと、ネーミングの大切さは分かっているけど、分かっていながら手抜きをしているような人には言わない）

2018-02-23 02:40 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> +	public TwitterPostDoFn(String[] oauth) {
あー、Main.MyOptionは可視性をpublicにしても他のクラスから参照できないのね。
MyOptionをconstantsパッケージあたりにでも突っ込んであげればいいよー。

2018-02-24 00:56 UTC, yoshioH approved these changes

2018-02-24 00:56 UTC, yoshioH commented on src/main/java/doFn/TwitterPostDoFn.java
> +		Twitter lgbot = initOauth().getInstance();
getInstanceまでinitOauthでやっちゃえば？

2018-02-24 00:56 UTC, yoshioH commented on src/main/java/constants/SiteType.java
> +	public String toString() {
Overrideなら@Overrideアノテーションをつけましょう。

2018-02-24 00:56 UTC, yoshioH commented on src/main/java/Main.java
> +//				.apply("Convert to Some Object", ParDo.of(new ConvertDoFn()))
コメントアウトするくらいなら行ごと削除しましょう。

2018-02-27 13:53 UTC, yoshioH commented on src/main/java/constants/SiteType.java
> +	public static boolean judgeSiteType(String siteTypeOfPubSubMesagesURL) {
isOldにするのが一般的です。

2018-02-27 13:56 UTC, yoshioH commented on src/main/java/Main.java
> +		MyOption runtimeOptionFromCommandLineArguments = PipelineOptionsFactory.fromArgs(args)
From以降は不要です。

2018-02-27 13:57 UTC, yoshioH commented on src/main/java/constants/SiteType.java
> +	public static boolean judgeSiteType(String siteTypeOfPubSubMesagesURL) {
引数のOf以降は不要です。

2018-02-27 13:58 UTC, yoshioH commented
動くと思うので、僕のレビューは終わりにします。

2018-02-28 03:31 UTC, ryutah requested changes
コンパイルエラーだけ確認おなしゃす。
平山さんががっつりレビューしてくれてるんで、他のコメントはわりとどうでもいいです。

2018-02-28 03:31 UTC, ryutah commented on src/main/java/constants/SiteType.java
> +	old("old"), modern("modern");
列挙型はアッパーケース使うのが一般的かと。
`OLD`、`MODERN`とかですね。

2018-02-28 03:31 UTC, ryutah commented on src/main/java/doFn/TwitterPostDoFn.java
> +
ここコンパイルエラー出てない？

2018-02-28 03:31 UTC, ryutah commented on src/main/java/doFn/TwitterPostDoFn.java
> +
TwitterインターフェースがSerializable継承してるし、コンストラクタでTwitterインスタンス生成してメンバはTwitterインスタンスだけにしたほうが良さそう感。

2018-02-28 07:23 UTC, yoshioH commented
【2/27追記】について。
今気づきました。Slackで一週間前のコメントを修正したから気づいてくださいというのと同じくらいのむちゃぶりです。
タイポやちょっとした間違いの修正などであればよいのですが、時間が経った一つのコメントを更新するのは混乱のもとなのでやめましょう。新しいコメントを追加してください。完全に情報が埋もれてます。

2018-02-28 07:26 UTC, ryutah commented
あーホントだ気づかなかったw
こういうケースは、Push後に新しくコメント追加する感じにしたほうがいいすよ。
必要ならメンションとかつけて。

2018-02-28 13:31 UTC, kazuki-m commented
@yoshioH 
投げやりな修正をしたつもりは無いですが、確認が足りなかったです。
レビューありがとうございました。

2018-02-28 14:09 UTC, kazuki-m commented on src/main/java/doFn/TwitterPostDoFn.java
> +
未コミットのテストクラスを作成していたため、エラーになっておらず、見落としていました。
修正します。

2018-03-01 03:28 UTC, yoshioH commented
何の確認が足りなかったの？何に気を付けてどう修正したの？
認識が欠けていたとか確認が不足していたのような紋切り型の表現に終始して、**何**の説明がないから投げやりなんだよ？
ツールの使い方でもあるんだけど、お互いが何を考えているのか経緯を説明/確認するためにレビュー指摘へのコメントが相互にできるようになっているんだよ。

加えて言うと、これまでの会話の中で**何**に対する意識が低いから、責務やオブジェクト指向を学ぶことは時期尚早だと判断して、**何**の具体的なパターンを知る手段としてリーダブルコードを勧めたんだよ。

2018-03-01 03:37 UTC, yoshioH commented
本格的にプログラミングを始めて半年ということを考えると、かなり早いペースで成長していると思います。この調子で成長すれば、近いうちに僕なんか軽く超える実力になるでしょう。ただ、今のうちに等身大のスキルをしっかり認識しておかないと、よく聞く勘違いフリーランスエンジニアになります。
クラウドサービスやフレームワークが発達している昨今は、自分の実力を錯覚しやすいので気をつけてくださいね。

2018-03-01 03:38 UTC, yoshioH commented
本格的にプログラミングを始めて半年ということを考えると、かなり早いペースで成長していると思います。この調子で成長すれば、近いうちに僕なんか軽く超える実力になるでしょう。ただ、今のうちに等身大のスキルをしっかり認識しておかないと、よく聞く勘違いフリーランスエンジニアになります。
クラウドサービスやフレームワークが発達している昨今は、自分の実力を錯覚しやすいので気をつけてくださいね。

2018-03-01 03:39 UTC, yoshioH commented
誤操作でクローズしてしまいましたので、再オープンします。
ごめんなさい。

2018-03-01 03:40 UTC, ryutah commented
熱いコメントからの誤操作クローズで不覚にも笑ってしまった。

2018-03-01 13:37 UTC, kazuki-m commented
今回の指摘事項だと@overrideが必須の理由、
変数名に情報を埋め込むことは意識して修正しました。
判定メソッドの置き場所は、使われる側のクラスに書いた方が今後追加あったときに、ロジックが重複しない位の認識のため、
何に気を付けてどう修正したかまでは出来てないです。

知識が無く、指摘されたことを調べて、初めて知識を断片的に得ている状態なので、
とりあえず、リーダブルコード読みます。

たしかに、データ処理のプログラム動いたときは割と感動しましたし、自分の実力錯覚しそうになるので、気をつけます。

2018-03-02 02:06 UTC, yoshioH commented
あー、そうか、最初に指摘したtoStringのOverrideは**必須ではない**ってのが上手く伝えられてなかったね。文章長いし分かりにくかったね、ごめんね。

メンバ変数がlabelって名前になって意図が良く伝わったよ。でも、それなら尚のことtoStringじゃなくてgetLabelでも、それこそ可視性をprivateからpublicにしてもよくないかな？
「新たなクラス作成したらtoStringオーバーライドするという認識」って表現からは「何も考えずOverrideしましょう」って受け取れるよ。
（ただ、toStringを意識してクラスを設計するのは良い習慣だと思います）

2018-03-02 02:12 UTC, yoshioH commented
>判定メソッドの置き場所は、使われる側のクラスに書いた方が今後追加あったときに、ロジックが重複しない位の認識のため、

何に気を付けたかについては、この理由で十分だよ！だから、怖がらずにそれをアピールして。

2018-03-02 02:22 UTC, yoshioH commented
あー、”Java toString”でググると、「JavaのtoStringメソッドは常にオーバーライドする」って記事がトップに出てきちゃうのか。Effective Javaの内容を初心者が見たらそりゃ混乱するか。

2018-03-02 15:01 UTC, kazuki-m commented
言葉足らずですみません、
オーバーライドしたら@Overrideのアノテーションが必須という意味でした。

前回の指摘は文字列を返すという処理であるならば、toStringの方がメソッド名として適切という意味で受け取ってます。

2018-04-08 02:17 UTC, kazu728 commented
AOPですが、システムの規模、clouddataflowで動かない可能性があるとのことですので、実装しませんでした。

修正部分、テストコードを特に見て頂きたいです。
上位の関心事（予測値、実際の値、イコール判定）以外が目立たないよう、
既に品質が担保されているものを別クラスに書き出しました。

2018-04-21 10:06 UTC, closed without merging